replicaCount: 3

image:
  repository: ghcr.io/kiranshet/local-devops-project
  tag: f16ac9c7ac28389ba759da48dafd8601ad6dd6c6
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

environment:
  name: prod
  version: v2
