replicaCount: 3

image:
  repository: ghcr.io/kiranshet/local-devops-project
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

environment:
  name: prod
  version: v3
