replicaCount: 3

image:
  repository: ghcr.io/kiranshet/local-devops-project
  tag: c867bbac3079663000cbfec58bb2e8bbe21b8114
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

environment:
  name: prod
  version: v2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
